### ISSUE TITLE
Podstawy programowania webowego

### ISSUE THREAD

**Issue by lukaszo** [hackerspace-silesia/warsztaty#3]
@galuszkak @michalpipa @firemark @palid Mary Pieroszkiewicz
- stworzyć plik dla warsztatu
- przygotować plan warsztatu

**Comment by firemark** [comment]
@galuszkak @michalpipa @firemark @palid Mary Pieroszkiewicz
Zamierzamy się spotkać, kiedyś by omówić temat? Jakie pasują wasze terminy? Można nawet przez skype, bo tak tekstowo to się nigdy nie dogadamy

**Comment by Palid** [comment]
Postaram się za tydzień wpaść na spotkanie HSowe, wtedy myślę będzie 
można pozałatwiać wszystko.

**Comment by firemark** [comment]
Ok, reszta?
