### ISSUE TITLE
Przygotować dystrybucję Linuksa na dysku USB

### ISSUE THREAD

**Issue by lukaszo** [hackerspace-silesia/warsztaty#6]
@soltysh @kwadrat @michalpipa

Potrzebna jest dystrybucja na warsztaty. Powinna zawierać:
- python
- php
- edytor
- itd. (dopiszcie co jeszcze)

**Comment by firemark** [comment]
Moim zdaniem najlepiej będzie wybrać xubuntu - czyli ubuntu + xfce - jest lekkie, 
Python, php, ruby to myślę że pikuś. 
Myślę nad zainstalowaniem nginxa (albo apache z php + .htacess bo why not) - przyda się dla web.
Edytor… Tu nie jestem pewny który wybrać. Moi kandydaci:
- sublime3 (darmowa wersja - nie wiem czy licencja na to pozwala?)
- Eclipse 
- Aptana
- Jakiś soft z jetbrain - Pycharm / PHPStorm?

I to chyba nam starczy… oczywiście dojdzie dodatkowy soft, frameworki, narzędzia. Ale to w trakcie.

**Comment by kwadrat** [comment]
Użyłem Knoppix 7.4 EN w trybie Read-Only (aby USB nie było zapisywane). Problematyczne było blokowanie/niedziałanie skryptów na www.batmat.pl przez dodatek NoScript do Iceweasel. Mam te 7 pendrive'ów, komu je przekazać?

**Comment by lukaszo** [comment]
Zamykam ticket. Mamy dyski z Linuxem. Co do przekazania umówimy się mailowo
